name: pubdates
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^1.1.0
  bloc: ^8.0.2
  bloc_concurrency: ^0.2.0
  flutter_bloc: ^8.0.1
  provider: ^6.0.0
  pubspec_lock: ^3.0.1
  pubspec_parse: ^1.2.0
  path: ^1.8.0
  process_run: ^0.12.3
  http: ^0.13.4
  html: ^0.15.0
  flutter_widget_from_html_core: ^0.8.5

  # Native
  file_selector: ^0.8.3
  file_selector_macos: ^0.0.4
  file_selector_windows: ^0.8.2
  file_selector_linux: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
